scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_037.inp data_CATEGORY_KEY_NAME_DIC save_INVALID_CATEGORY_KEY_NAME: WARNING, attribute '_category_key.name' references the '_undefined.item' data item that is not defined in the given dictionary.
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_037.inp data_CATEGORY_KEY_NAME_DIC save_INVALID_CATEGORY_KEY_NAME: WARNING, data item '_valid_category_key_name.item_2' is referenced as the category key, however, it does not belong to the given category ('VALID_CATEGORY_KEY_NAME' instead of 'INVALID_CATEGORY_KEY_NAME').
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_037.inp data_CATEGORY_KEY_NAME_DIC save_INVALID_CATEGORY_KEY_NAME_IN_FUNCTION: WARNING, attribute '_category_key.name' is not compatible with the 'Function' definition class -- the only compatible '_definition.class' attribute values are ['Set', 'Loop'].
